services:
  mongo:
    image: mongo:7
    container_name: trovacampo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-dati:/data/db

volumes:
  mongo-dati:
